package com.dovar.router_compiler;

import com.dovar.router_annotation.Router;
import com.google.auto.service.AutoService;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.TypeName;
import com.squareup.javapoet.TypeSpec;

import java.util.HashSet;
import java.util.Set;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.Filer;
import javax.annotation.processing.Messager;
import javax.annotation.processing.ProcessingEnvironment;
import javax.annotation.processing.Processor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.tools.Diagnostic;

@AutoService(Processor.class)
@SupportedSourceVersion(SourceVersion.RELEASE_7)
public class RouterProcessor extends AbstractProcessor {
    private final String proxyClassPackage = "com.touchtv.router";
    private final String proxyClassSimpleName = "RouterInitProxy";
    private final String routerInjectorPackage = "com.touchtv.router_api.compiler";
    private final String routerInjectorSimpleName = "RouterInjector";
    private final String BaseApplicationLogicPackage = "com.touchtv.router_api.router";
    private final String BaseApplicationLogicSimpleName = "BaseApplicationLogic";

    private Filer filer;
    private Messager messager;

    @Override
    public Set<String> getSupportedAnnotationTypes() {
        Set<String> supportTypes = new HashSet<>();
        supportTypes.add(Router.class.getCanonicalName());
        return supportTypes;
    }

    @Override
    public synchronized void init(ProcessingEnvironment processingEnv) {
        super.init(processingEnv);
        filer = processingEnv.getFiler();
        messager = processingEnv.getMessager();
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        messager.printMessage(Diagnostic.Kind.NOTE, "process router...");

        if (annotations.isEmpty()) {
            return false;
        } else {
            Set<? extends Element> moduleList = roundEnv.getElementsAnnotatedWith(Router.class);
            generateModulesProviderMappingInit(moduleList);
            return true;
        }
    }

    private void generateModulesProviderMappingInit(Set<? extends Element> modules) {
        ClassName application = ClassName.get("android.app", "Application");
        ClassName baseApplicationLogic = ClassName.get(BaseApplicationLogicPackage, BaseApplicationLogicSimpleName);
        MethodSpec registerModule = MethodSpec.methodBuilder("registerModule")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(TypeName.VOID)
                .addParameter(Class.class, "logicClass")
                .addParameter(application, "app")
                .addStatement("if (logicClass == null) return")
                .beginControlFlow("try")
                .addStatement("$T instance = ($T)logicClass.newInstance()", baseApplicationLogic, baseApplicationLogic)
                .addStatement("instance.setApplication(app)")
                .addStatement("instance.onCreate()")
                .endControlFlow("catch ($T e) { e.printStackTrace(); }", ClassName.get(Exception.class))
                .build();

        MethodSpec.Builder initBuilder = MethodSpec.methodBuilder("init")
                .addModifiers(Modifier.PUBLIC)
                .returns(TypeName.VOID)
                .addParameter(application, "app")
                .addParameter(String.class, "processName");

        for (Element e : modules
                ) {
            if (e.getKind() == ElementKind.CLASS) {
                String name = e.getAnnotation(Router.class).process();
                ClassName className = ClassName.get((TypeElement) e);
                initBuilder.beginControlFlow("if(processName!=null&&processName.equals(\"" + name + "\"))")
                        .addStatement("$N($T.class,app)", registerModule, className)
                        .endControlFlow();
            }
        }


        TypeSpec providerInit = TypeSpec.classBuilder(proxyClassSimpleName)
                .addJavadoc("DO NOT EDIT!!! IT WAS GENERATED BY ROUTER.")
                .addModifiers(Modifier.PUBLIC)
                .addSuperinterface(ClassName.get(routerInjectorPackage, routerInjectorSimpleName))
                .addMethod(registerModule)
                .addMethod(initBuilder.build())
                .build();
        try {
            JavaFile.builder(proxyClassPackage, providerInit)
                    .build()
                    .writeTo(filer);
        } catch (Throwable e) {
            e.printStackTrace();
        }
    }

}
